DOCKER_CONFIG:
# 2.2 Ensure network traffic is restricted between containers on the default bridge (Manual) 
docker_config:
  proxy:
    enable: true
    http_url: "http://192.168.15.21:1080"
    https_url: "http://192.168.15.21.1080"
    no_proxy_url: "gitlab.stackops.ir, registry.stackops.ir,127.0.0.0/8"

  # 2.14 Ensure centralized and remote logging is configured (Manual)
  log_driver:
    enable: true
    name: "syslog"

  # set this option to false if you want to use "syslog" log driver
  log_opt:
    enable: false
    labels: "{{ inventory_hostname }}"
    max_file: 5
    max_size: 100M
  
  # 2.3 Ensure the logging level is set to 'info' (Manual)
  log_level:
    enable: true
    level: "info"
  
  # 2.15 Ensure containers are restricted from acquiring new privileges (Manual)
  no_new_privileges:
    enable: true


  mirror_registry:
    enable: true
    urls: "https://docker.arvancloud.ir"
  # 2.5 Ensure insecure registries are not used (Manual)
  insecure_registry:
    enable: false
    urls: "https://test.mecan.ir"

  #2.16 Ensure live restore is enabled (Manual)
  live_restore:
    enable: true
  # 2.19 Ensure that experimental features are not implemented in production (Manual)
  experimental:
    enable: false
    
  # 2.2 Ensure network traffic is restricted between containers on the default bridge (Manual) 
  icc:
    enable: false
  # 2.4 Ensure Docker is allowed to make changes to iptables (Manual)
  iptables:
    enable: true
  # 2.6 Ensure aufs storage driver is not used (Manual)
  # 2.7 Ensure devicemapper storage driver is not used (Manual)
  storage_driver:
    enable: true
    name: "overlay2"
    
  # 2.17 Ensure Userland Proxy is Disabled (Manual)
  user_land_proxy:
    enable: false

  # 2.9 Ensure the default ulimit is configured appropriately (Manual)
  default_ulimits:
    enable: true
    nofile:
      name: nofile
      hard: 10000
      soft: 10000
    nproc:
      name: nproc
      hard: 2048
      soft: 1024
  # 2.11 Ensure the default cgroup usage has been confirmed    (Manual)
  cgroup_parent:
    enable: true
    name: "omidpay.slice"
  
