---
- name: Ensure a Separate partition for containers has been created
  ansible.builtin.command: grep '/var/lib/docker' /proc/mounts
  register: containers_partition
  ignore_errors: yes
  tags: 
   - hosts_configuration
   - section-1

- name: Partition for containers has NOT been configured
  ansible.builtin.debug:
    msg: "Separate Partition '/var/lib/docker' for containers has NOT been configured."
  when: containers_partition.stdout_lines | length == 0
  tags: 
   - hosts_configuration
   - section-1



- name: Ensure only trusted users are allowed to control Docker Daemon
  ansible.builtin.command: getent group docker
  register: docker_group
  ignore_errors: yes
  tags: 
   - hosts_configuration
   - section-1


- name: Show the members of the docker group
  ansible.builtin.debug:
    msg: "Members of the docker group: {{ docker_group.stdout }}"
  when: docker_group.stdout != ""
  tags: 
   - hosts_configuration
   - section-1


- name: Ensure auditd is installed
  ansible.builtin.package:
    name: auditd
    state: present
  tags: 
   - hosts_configuration
   - section-1


- name: Ensure auditing is configured for the 1.1.3 to 1.1.18
  ansible.builtin.lineinfile: 
    path: /etc/audit/audit.rules
    line: "{{ item }}"
    state: present
  loop: 
   - -w /usr/bin/dockerd -k docker
   - -w /run/containerd -k docker
   - -a exit,always -F path=/run/containerd -F perm=war -k docker
   - -a exit,always -F path=/var/lib/docker -F perm=war -k docker
   - -a exit,never -F dir=/var/lib/docker/volumes
   - -a exit,never -F dir=/var/lib/docker/overlay2
   - -w /etc/docker -k docker
   - -w /usr/lib/systemd/system/docker.service -k docker
   - -w /run/containerd/containerd.sock -k docker
   - -w /var/run/docker.sock -k docker
   - -w /etc/default/docker -k docker
   - -w /etc/docker/daemon.json -k docker
   - -w /etc/containerd/config.toml -k docker
   - -w /etc/sysconfig/docker -k docker
   - -w /usr/bin/containerd -k docker
   - -w /usr/bin/containerd-shim -k docker
   - -w /usr/bin/containerd-shim-runc-v1 -k docker
   - -w /usr/bin/containerd-shim-runc-v2 -k docker
   - -w /usr/bin/runc -k docker
  notify: Restart auditd
  tags: 
   - hosts_configuration
   - section-1

- name: Ensure that the version of Docker is up to date
  ansible.builtin.shell: docker --version | cut -d ' ' -f3 | sed 's/,//'
  register: docker_version
  ignore_errors: yes
  tags: 
   - hosts_configuration
   - section-1

- name: Show current docker version
  ansible.builtin.debug:
    msg: "Current Docker version is {{ docker_version.stdout }}"
  when: docker_version.stdout != ""
  tags: 
   - hosts_configuration
   - section-1

- name: Update the docker package to the latest version
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin 
    - docker-compose-plugin
  when: docker_version.stdout is version("{{ docker_latest_version }}", '<') 
  tags: 
   - hosts_configuration
   - section-1

