#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/daemon_configuration_file
file_permissions:
#3.1 Ensure that the docker.service file ownership is set to root:root (Automated)
#3.2 Ensure that docker.service file permissions are appropriately set (Automated)
  - path: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r' #'0644'
#3.3 Ensure that docker.socket file ownership is set to root:root (Automated)
#3.4 Ensure that docker.socket file permissions are set to 644 or more restrictive (Automated)
  - path: /usr/lib/systemd/system/docker.socket
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r' #'0644'
# 3.5 Ensure that the /etc/docker directory ownership is set to root:root (Automated)
# 3.6 Ensure that /etc/docker directory permissions are set to 755 or more restrictively (Automated)
  - path: /etc/docker
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx' #'0755'

# 3.7 Ensure that registry certificate file ownership is set to root:root (Manual)
# 3.8 Ensure that registry certificate file permissions are set to 444 or more restrictively (Manual)  
  - path: /etc/docker/certs.d/
    owner: root
    group: root
    mode: 'u=r,g=r,o=r' #'0444'

# 3.15 Ensure that the Docker socket file ownership is set to root:docker (Automated)

  - path: /var/run/docker.sock
    owner: root
    group: docker
    mode: 'u=rw,g=rw' #'0660'