---
# 4.1 Ensure that a user for the container has been created (Manual)
- name: include user for containers CIS 4.1
  include_tasks: user_for_containers.yml
  tags: 
  - user_for_containers
  - container_images_and_file_configuration
  - section-4

# 4.5 Ensure Content trust for Docker is Enabled (Manual)
- name: include enable content trust for docker CIS 4.5
  include_tasks: enable_content_trust.yml
  tags: 
  - enable_content_trust
  - container_images_and_file_configuration
  - section-4

# 4.6 Ensure that HEALTHCHECK instructions have been added to container images (Manual)
- name: include check healthcheck instruction in container images CIS 4.6
  include_tasks: check_healthcheck.yml
  tags: 
  - check_healthcheck
  - container_images_and_file_configuration
  - section-4

# 4.7 Ensure update instructions are not used alone in Dockerfiles (Manual)
- name: include check update instruction in container images CIS 4.7
  include_tasks: check_update_instruction.yml
  tags: 
  - check_update_instruction
  - container_images_and_file_configuration
  - section-4

# 4.9 Ensure that COPY is used instead of ADD in Dockerfiles (Manual)
- name: include check ADD instruction in container images CIS 4.9
  include_tasks: check_add_in_dockerfile.yml
  tags: 
  - check_add_in_dockerfile
  - container_images_and_file_configuration
  - section-4