#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/daemon_configuration
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: yes